kudo form component
lubomir1618/kudo pull request #18
Opened 2020-02-28 14:01 UTC by lenkastanekova

2020-02-28 14:10 UTC, lubomir1618 approved these changes

2020-02-28 14:15 UTC, lukasorgovan requested changes

2020-02-28 14:15 UTC, lukasorgovan commented on src/client/components/KudoForm/KudoForm.tsx
> +PEOPLE.map((folk: any) => {
do not remap to xx_yyy, it is not necessary, value can have spaces if it is a string.

2020-02-28 14:15 UTC, lukasorgovan commented on src/client/components/KudoForm/KudoForm.tsx
> +PEOPLE.map((folk: any) => {
do it responsive, fix validation for empty string text

2020-03-02 08:08 UTC, lukasorgovan approved these changes

2020-03-02 08:08 UTC, merged